/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./titan_lms/templates/**/*.html",
    "./titan_lms/static/js/**/*.js",
    "./titan_lms/routes/**/*.py"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bfc5e4",
        "on-surface": "#1c1c17",
        "tertiary-container": "#cba72f",
        "on-primary-fixed-variant": "#0040a0",
        "on-error": "#ffffff",
        "secondary-fixed": "#dce1ff",
        "secondary": "#575d78",
        "surface-container-low": "#f6f3eb",
        "tertiary-fixed": "#ffe088",
        "surface": "#fcf9f1",
        "inverse-surface": "#31312b",
        "primary": "#0054cb",
        "primary-container": "#2c6dec",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#5b617d",
        "surface-tint": "#0056d0",
        "surface-bright": "#fcf9f1",
        "outline": "#737786",
        "on-secondary-fixed": "#141a32",
        "primary-fixed": "#dae2ff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#4e3d00",
        "background": "#fcf9f1",
        "on-tertiary-fixed-variant": "#574500",
        "secondary-container": "#d8defe",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe8e0",
        "surface-container": "#f1eee6",
        "on-surface-variant": "#424654",
        "inverse-on-surface": "#f3f1e9",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#b1c5ff",
        "on-tertiary": "#ffffff",
        "tertiary": "#735c00",
        "on-primary-fixed": "#001847",
        "surface-container-highest": "#e5e2da",
        "outline-variant": "#c2c6d7",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#241a00",
        "on-background": "#1c1c17",
        "surface-dim": "#dcdad2",
        "surface-variant": "#e5e2da",
        "error": "#ba1a1a",
        "inverse-primary": "#b1c5ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465f",
        "tertiary-fixed-dim": "#e9c349"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xxl": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "lg": "24px",
        "xl": "32px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "md": "16px",
        "xs": "4px",
        "base": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "1", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
